// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE3Q3d2zgJQMlBfgW7SnKYR0ww40lN5Ss',
    appId: '1:86359871031:web:b982a8c2048f45c0cfb9b2',
    messagingSenderId: '86359871031',
    projectId: 'fitzz-637e0',
    authDomain: 'fitzz-637e0.firebaseapp.com',
    storageBucket: 'fitzz-637e0.firebasestorage.app',
    measurementId: 'G-NEHF67LDWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBavddeEvBwZ5Hh8TVRwvYtzgnEq2ClG7U',
    appId: '1:86359871031:android:7c969b27e464b56ecfb9b2',
    messagingSenderId: '86359871031',
    projectId: 'fitzz-637e0',
    storageBucket: 'fitzz-637e0.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE3Q3d2zgJQMlBfgW7SnKYR0ww40lN5Ss',
    appId: '1:86359871031:web:e7ee083fdb95887dcfb9b2',
    messagingSenderId: '86359871031',
    projectId: 'fitzz-637e0',
    authDomain: 'fitzz-637e0.firebaseapp.com',
    storageBucket: 'fitzz-637e0.firebasestorage.app',
    measurementId: 'G-M3BT70Q7V8',
  );
}
